apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app
  labels:
    app: nodejs
spec:
  replicas: 2  # Two replicas for load balancing
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
        - name: nodejs-container
          image: node:14  # Use official Node.js Docker image
          ports:
            - containerPort: 8080  # The port inside the container
          env:
            - name: NODE_ENV
              value: "production"  # Example environment variable for production setup
