apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80  # Exposed service port
      targetPort: 8081  # Points to the container's 8081 port
      nodePort: 30081  # Exposed port on the node (NodePort type)
  type: ClusterIP  # Using NodePort to expose the service externally

